name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Paso 1: Hacer checkout del código
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Paso 2: Autenticarse en Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # ¡Aquí está el cambio!

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Compilar la aplicación Angular
      - name: Build Angular app
        run: npm run build -- --configuration production

      # Paso 5: Renombrar index.csr.html a index.html
      - name: Rename index.csr.html to index.html
        run: |
          if [ -f dist/frontend-layer/browser/index.csr.html ]; then
